version: '3.8'

services:

  database:
    image: planetly/postgres:joshua
    build:
      context: .
      dockerfile: Dockerfile-postgres 
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8500:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./.postgres-init/scripts:/docker-entrypoint-initdb.d
      - ./.postgres-init/load_data.sh:/var/opt/load_data.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 120s
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    image: planetly/api:joshua
    build:
      context: ./api
      dockerfile: Dockerfile-api 
    # command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    command: ./wait-for-it.sh database:5432 -s -t 0 -- uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api/.:/app
    ports:
      - 8080:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:postgres@database:5432/planetly
    depends_on:
      database:
        condition: service_healthy
    

