version: '3'

services:

  database:
    image: planetly/postgres:joshua
    build:
      context: .
      dockerfile: Dockerfile-postgres 
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8500:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./.postgres-init/scripts:/docker-entrypoint-initdb.d
  
  api:
    image: planetly/api:joshua
    build:
      context: ./api
      dockerfile: Dockerfile-api 
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api/.:/app
    ports:
      - 8080:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:postgres@database:5432/planetly
    depends_on:
      - database

